name: Metaphor DBT Metadata
description: Publish DBT metadata to Metaphor
inputs:
  looker-base-url:
    description: Base URL for Looker API
    required: true

  looker-client-id:
    description: Client ID for Looker API
    required: true

  looker-client-secret:
    description: Client secret for Looker API
    required: true

  lookml-dir:
    description: Path to LookML project directory
    required: true

  project-source-url:
    description: The URL pointing to the project source code directory
    required: false
    default: ''

  connection-map:
    description: A JSON file containing the Looker database connection configs
    required: true

  s3-path: 
    description: S3 path for outputting the metadata
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.looker-base-url }}
    - ${{ inputs.looker-client-id }}
    - ${{ inputs.looker-client-secret }}
    - ${{ inputs.lookml-dir }}
    - ${{ inputs.project-source-url }}
    - ${{ inputs.connection-map }}
    - ${{ inputs.s3-path }}
